Design/trading table
turbinecrew/turbin_electrical pull request #19
Opened 2024-12-09 07:36 UTC by nrkcode

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

<details>
<summary>design/trading pr 참고로 올립니</summary>
<div markdown="1">

 - [🔧 : npm install tailwindcss-animate](https://github.com/turbinecrew/turbin_electrical/commit/372742ded47018a1ad72cdafca7eb824d94d8bb6)
        - fix라고 해야 하나 고민하다가 이렇게 했습니다

### 카드 컴포넌트 제작
예시 이미지
![image](https://github.com/user-attachments/assets/a0fc02df-f405-40b2-b131-7cdf89ec675e)
(내용들은 아무데서나 가져온거라 의미 없습니다..)
> [🎨 : card component 제작](https://github.com/turbinecrew/turbin_electrical/commit/37279635c54bfd190bf405f28ee3c21f74bb6039)
> [🎨 : 카드 컴포넌트 ui 추가 작업](https://github.com/turbinecrew/turbin_electrical/commit/a40399f762f4a9d28a3b79bef2388ffd09d96317)
- 일반 카드
    - 라운드, 그림자 css가 기본값으로 지정되어 있음
    - [props] `isColored`: true: 녹색 그라데이션 / false: 흰색 반투명 배경
- 타이틀카드
    - [props] 큰 제목 title, 부제목 lowerTitle
    - title, lowerTitle과 children을 flex-col로 정렬해두었음
- 미니카드
    - [props] title: 제목 string, value: 값 string | number, unit: 단위 (예시에서 원) string, className: 스타일지정 string
    - 일반 카드의 isColored={false} 값으로 지정되어있음
    - children 없음
- 내용카드
    - div 태그만 있으며 추후 필요할 것 같아서 넣음

</div>
</details>

KAN-21,KAN-22

design/tradingtable 거래 상세 테이블 ui

> app
>└── trading-table
> ----├── columns.tsx
> ----├── data.tsx
> ----└── page.tsx
>└── components
> ----└── common
> --------└── data-table
> ------------└── page.tsx

- `columns.tsx`(client component): 열 정의
- `data-table.tsx` (client component): `<DataTable />`컴포넌트가 들어있는 곳
- `page.tsx` (server component): 테이블을 렌더링 하는 곳
- `data.tsx` Fetch data from your API here. 임시로 생성한 mock데이터 넣어두었습니다.
- 
![image](https://github.com/user-attachments/assets/88861659-a189-43e1-8063-a6f6caaef356)

- 컬럼 구성
    - 거래 시간: "2023-12-04 12:00".
    - 발전소 이름: "서울 태양광 발전소".
    - 거래량: "500 MWh".
    - 입찰 가격: "₩70/kWh".
    - 매칭 여부: "매칭", "미매칭".
 ```
export type EnergyTrade = {
	id: string
	tradeTime: string // 거래 시간
	plantName: string // 발전소 이름
	volume: string // 거래량
	bidPrice: string // 입찰 가격
	matchingStatus: "matched" | "unmatched" // 매칭 여부
}
```

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-12-09 08:13 UTC, seongyun4359 approved these changes
- [x] "✅ LGTM"

고생하셨습니다

2024-12-09 08:27 UTC, keeprok requested changes
수고하셨습니다

2024-12-09 08:27 UTC, keeprok commented on src/app/(main)/trading/trading-table/columns.tsx
> +export type EnergyTrade = {
이부분 TColumns로 변경하시면될거같아요

2024-12-09 08:27 UTC, keeprok commented on src/app/(main)/trading/trading-table/data.tsx
> +export default getData
export async function 으로 해주세요

2024-12-09 08:27 UTC, keeprok commented on src/components/common/button/index.tsx
> +export default Button
여기도요

2024-12-09 08:27 UTC, keeprok commented on src/components/common/data-table/index.tsx
> +interface DataTableProps<TData, TValue> {
Type DataTablePT로 작성부탁드려요

2024-12-09 08:36 UTC, nrkcode commented on src/components/common/data-table/index.tsx
> +interface DataTableProps<TData, TValue> {
```
export type DataTablePT = {
	id: string
	tradeTime: string // 거래 시간
	plantName: string // 발전소 이름
	volume: string // 거래량
	bidPrice: string // 입찰 가격
	matchingStatus: "matched" | "unmatched" // 매칭 여부
}
```
로 수정했습니다

2024-12-09 17:05 UTC, nrkcode commented on src/components/common/data-table/index.tsx
> +interface DataTableProps<TData, TValue> {
```
export type DataTablePT = {
	id: string
	tradeTime: string // 거래 시간
	plantName: string // 발전소 이름
	volume: string // 거래량
	bidPrice: string // 입찰 가격
	matchingStatus: "matched" | "unmatched" // 매칭 여부
}

```
변경했습니다!

2024-12-09 17:05 UTC, nrkcode commented on src/app/(main)/trading/trading-table/columns.tsx
> +export type EnergyTrade = {
![image](https://github.com/user-attachments/assets/2c3a6b69-fccc-462d-b804-d800260044d8)

변경했습니다!

2024-12-09 18:04 UTC, nrkcode commented
[🚚 : 컨벤션에 맞게 수정하고component, table 파일구조 변경](https://github.com/turbinecrew/turbin_electrical/pull/19/commits/20d9854d3a5d0dd86520fee39bad2b3a5ad08eea)
![image](https://github.com/user-attachments/assets/119c236a-11a4-42e6-9ab6-6226597f97ac)
shadcn/ui 컴포넌트를 폴더화하고 data-table을 table 하위로 넣었습니다.

2024-12-10 09:02 UTC, keeprok requested changes

2024-12-10 09:02 UTC, keeprok commented on src/app/(main)/trading/trading-table/data.tsx
> +export default async function getData(): Promise<DataTablePT[]> {
이경우는 async가 필요없지않을까요 ??

2024-12-10 09:02 UTC, keeprok commented on src/app/(main)/trading/trading-table/page.tsx
이런 파일같은경우 custom파일이 더좋아보이는데요

2024-12-10 09:02 UTC, keeprok commented on src/components/common/button/index.tsx
> +interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
Type으로변경해주세여

2024-12-10 17:13 UTC, nrkcode reviewed
[⚡️ : 컨벤션에 맞게 수정하고 TradingDataTable 작업](https://github.com/turbinecrew/turbin_electrical/pull/19/commits/6762dfb728fb9430f94f0d1e0564bd7273ca46e5)

columns를 컨벤션에 맞게 getColumns 함수로 만들고 나니 페이지로 두면 넥스트의 특성(서버컴포넌트에서 클라이언트 컴포넌트의 함수 사용 불가)로 인해 작동 안하는 문제 발생
원래 trading 페이지에 컴포넌트로 넣으려던 테이블이기 때문에 클라이언트 컴포넌트로 만들었고 trading 페이지에서 TradingDataTable 컴포넌트 불러오면 정상작동하게 되었습니다.

근데 이러면 app/main에  trading-table이 있지 않아도 될 것 같네요
처음에 app/(main)/trading/trading-table 했던 것도 trading페이지 말고 테이블 확인용 페이지 따로 빼려는 의도였으니
custom으로 옮길까요?

2024-12-10 17:28 UTC, nrkcode commented
[⚡️ : 컨벤션에 맞게 수정하고 TradingDataTable 작업](https://github.com/turbinecrew/turbin_electrical/pull/19/commits/6762dfb728fb9430f94f0d1e0564bd7273ca46e5)

columns를 컨벤션에 맞게 getColumns 함수로 만들고 나니 페이지로 두면 넥스트의 특성(서버컴포넌트에서 클라이언트 컴포넌트의 함수 사용 불가)로 인해 작동 안하는 문제 발생
원래 trading 페이지에 컴포넌트로 넣으려던 테이블이기 때문에 클라이언트 컴포넌트로 만들었고 trading 페이지에서 TradingDataTable 컴포넌트 불러오면 정상작동하게 되었습니다.


...
근데 이러면 app/main에  trading-table이 있지 않아도 될 것 같네요
처음에 (main)/trading/trading-table 했던 것도 trading페이지 말고 테이블 확인용 페이지 따로 빼려는 의도였으니
custom으로 옮겼습니다

[🚚 : trading-table 파일 위치 변경 작업](https://github.com/turbinecrew/turbin_electrical/pull/19/commits/f4e34326d348e492c1e2c5725aaa241da32e228d)

```
custom
└── trading-table/
    ├── data-table.tsx
    ├── data.tsx
    ├── index.tsx // 원래 TradingDataTable
    └── Tcolumns.tsx
```

2024-12-10 17:29 UTC, nrkcode commented on src/components/common/button/index.tsx
> +interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
```
type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
	className?: string
}
```
변경했습니다

2024-12-10 17:30 UTC, nrkcode commented on src/app/(main)/trading/trading-table/page.tsx
변경했습니다!

2024-12-10 17:30 UTC, nrkcode commented on src/app/(main)/trading/trading-table/data.tsx
> +export default async function getData(): Promise<DataTablePT[]> {
```
export function getColumns(): ColumnDef<DataTablePT>[] {
	return [
```
변경했습니다

2024-12-10 17:31 UTC, nrkcode commented on src/app/(main)/trading/trading-table/Tcolumns.tsx
> +export const columns: ColumnDef<DataTablePT>[] = [
```
export function getColumns(): ColumnDef<DataTablePT>[] {
	return [
```
변경했습니다

2024-12-11 13:53 UTC, keeprok approved these changes
좋은데여 👍 async빼도 된다고 한부분은 설명은 적어드리진않았지만 지금부분에서는 필요없고 데이터 불러올때는 필요한 부분입니다 동기와 비동기의 차이점에서 오는부분이라 찾아보시면 좋을것같네요

2024-12-11 13:54 UTC, keeprok commented on src/app/(main)/trading/trading-table/Tcolumns.tsx
> +export const columns: ColumnDef<DataTablePT>[] = [
[🚚 : 파일이름, 타입, 함수 컨벤션에 맞게 수정](https://github.com/turbinecrew/turbin_electrical/pull/19/commits/372006c1de47590d033bb5539da989108ffc0119)

2024-12-12 06:24 UTC, merged