Feat/modal component
turbinecrew/turbin_electrical pull request #20
Opened 2024-12-10 05:42 UTC by seongyun4359

## 🔥 Issues

* issue: [KAN-12](https://dldudfhr425.atlassian.net/browse/KAN-12)

<br/>
<br/>

## 🎯 작업 내용
모달 공용 컴포넌트 제작했습니다.
배경, X (루시드 아이콘) 누르면, 모달 창 닫기
기본 디자인 일치 시켰습니다.
header, context, footer로 나눴습니다.
각 모달에 대한 상세 디자인은 추후 변경 예정입니다.

src/
├── app/
│   └── common/
│       └── modal/
│           └── index.tsx
├── components/
│   └── custom/
│       └── modal/
│           ├── sign-in-modal/
│           ├── sign-up-modal/

![image](https://github.com/user-attachments/assets/14da3de1-2d95-474d-9619-c4f0546d0e7c)
![image](https://github.com/user-attachments/assets/451c4c1d-9f97-4225-907b-8fcc74781dd5)

<br/>
<br/>

## ✅ 체크 리스트

- [ ] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-12-10 07:47 UTC, nrkcode requested changes

2024-12-10 07:47 UTC, nrkcode commented on tailwind.config.ts
> +	content: [
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->


  - [x] "🚧 재고해주시길.."

<!--
  - [x] "✅ LGTM"
-->

# Description

`content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],` 이거로 해야될거같아요

2024-12-10 09:02 UTC, keeprok commented
공용 모달이 아닌 로그인 가입 모달을 작성하신곳같아요

2024-12-10 09:12 UTC, seongyun4359 commented on tailwind.config.ts
> +	content: [
![image](https://github.com/user-attachments/assets/48668719-fa7d-435f-b04c-fb743c43db04)
수정했습니다 !

2024-12-10 09:13 UTC, keeprok requested changes

2024-12-10 09:13 UTC, keeprok commented on src/common/modal/index.tsx
> +	closeModal: () => void
이부분 boolean 가맞는것같네요

2024-12-10 09:13 UTC, keeprok commented on src/common/modal/index.tsx
> +				<button
이부분도 true false에맞게변형해주세요

2024-12-10 09:13 UTC, keeprok commented on src/common/modal/index.tsx
Props들 PT로 변경해주세요

2024-12-10 09:13 UTC, keeprok commented on src/components/custom/modal/sign-in-modal/index.tsx
> +	closeModal: () => void
Props를 받을필요가있을까요?

2024-12-10 09:13 UTC, keeprok commented on src/components/custom/modal/sign-in-modal/index.tsx
> +					Cancel
X버튼이잇는데 필요할까요 둘중하나만쓰면좋을것같아요

2024-12-10 09:13 UTC, keeprok commented on src/components/custom/modal/sign-up-modal/index.tsx
로그인 파일하고 수정할부분이 같아보여요

2024-12-10 09:13 UTC, keeprok commented on src/util/api/statics/region-overview/index.ts
이파일은 건들면 안됩니다

2024-12-11 13:50 UTC, keeprok commented
어 PR 답변같은경우는 제가 제시한부분에 대댓글의 답변으로  commit복사해서 붙여주시면 수정부분이 확실히 보일것같아요 
다음부터는 그렇게 부탁드릴게요

2024-12-11 14:49 UTC, nrkcode approved these changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->

  - [x] "✅ LGTM"


# Description

2024-12-13 03:31 UTC, seongyun4359 commented on src/common/modal/index.tsx
ㅇ.

2024-12-13 03:31 UTC, seongyun4359 commented on src/common/modal/index.tsx
sㅁㄴㅁㅇㄴㅁㅇㅇㄴ

2024-12-13 03:32 UTC, nrkcode commented on src/common/modal/index.tsx
> +				<button
안녕하세요

2024-12-13 03:32 UTC, merged