🎨: dashboard 디자인
turbinecrew/turbin_electrical pull request #24
Opened 2024-12-13 04:04 UTC by Giradon

차트 제외부분 디자인

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

[🎨: dashboard 디자인](https://github.com/turbinecrew/turbin_electrical/commit/b923ad53f67223f899ebed25d38d3df187ab6b96)
<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-12-13 04:11 UTC, seongyun4359 approved these changes
- [x] "✅ LGTM"

2024-12-13 12:08 UTC, nrkcode approved these changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->


  - [x] "✅ LGTM"

# Description

2024-12-14 03:53 UTC, keeprok reviewed
디자인을 완성하셨스면 pr에 완성된 디자인을 첨부해주세요 코드맘 보고서는 완성도를 저희는 알수가없어요
추가적으로 제목도 영어로 변경해주세요 아이콘은 commit용입니다

2024-12-16 04:38 UTC, keeprok requested changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->


  - [x] "🚧 재고해주시길.."


<!--
  - [x] "✅ LGTM"
-->

# Description

2024-12-16 04:38 UTC, keeprok commented on src/components/common/dashboard/index.tsx
> +"use client"
역할이없으면 지워주세요

2024-12-18 03:01 UTC, nrkcode approved these changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->


  - [x] "✅ LGTM"

# Description

2024-12-23 03:44 UTC, closed without merging