✨: 관리자 페이지 생성
turbinecrew/turbin_electrical pull request #25
Opened 2024-12-13 11:41 UTC by seongyun4359

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용
app/(main)/안에
manage/page.jsx 생성했습니다
[package-lock.json](https://github.com/turbinecrew/turbin_electrical/compare/feat/manage?expand=1#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) 이거는 lucide-react 업그레이드?된 것 같습니다.

<br/>
<br/>

## ✅ 체크 리스트

- [ ] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-12-13 12:09 UTC, nrkcode approved these changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->


  - [x] "✅ LGTM"


# Description

2024-12-14 03:19 UTC, Giradon approved these changes
- [x] "✅ LGTM"

2024-12-14 03:48 UTC, keeprok requested changes
제목 변경 , design 하신다 하셨는데 div로 끝내지않으셨으면해요 pr 2개 작성됬는데 최근 pr 하고 다른점이없습니다 이전pr은 연결을 미리 했다 지만 이pr은 왜생성됬는지 모르겠습니다

2024-12-14 08:39 UTC, keeprok approved these changes

2024-12-14 08:39 UTC, merged