design : trading
turbinecrew/turbin_electrical pull request #34
Opened 2024-12-23 04:41 UTC by nrkcode

## 🔥 Issues

<br/>
<br/>

## 🎯 작업 내용

> [⚡️ : card component 리팩토링, Trading page 디자인 변경](https://github.com/turbinecrew/turbin_electrical/commit/58eb5e3810405b39334cbe3503d470bf99e10e8f)

폴더별로 나눠져있던 card 컴포넌트들을 index 파일 하나로 합치고 기본 디자인 변경 (isColored 옵션- 터빈크루 라이트그린, 흰색(디폴트))

![image](https://github.com/user-attachments/assets/747f10fa-e94c-414c-8aad-8f3b149fc6ef)

>[🎨 : trading 페이지 레이아웃 변경](https://github.com/turbinecrew/turbin_electrical/commit/284f85b2c8d11daceb5115b4a966d9b54095c397)
>[🎨 : trading 페이지 디자인 변경](https://github.com/turbinecrew/turbin_electrical/commit/83dfe1a8bfad79b368a2262b04cd4a77b663b8e1) 

* 거래 상세 페이지 추가, 입찰 그래프 ui 등 추가
* 거래 테이블로 연결할 '거래관리' 버튼 추가

<br/>
<br/>

## ✅ 체크 리스트

- [] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-12-23 11:21 UTC, nrkcode commented
# 거래 페이지 디자인 변경
![image](https://github.com/user-attachments/assets/e8e6789e-edb0-45ea-ba70-5f5c9d9b7ad8)

* 차트, 테이블 추가 예정

2024-12-23 11:32 UTC, keeprok requested changes
수정해주세요

2024-12-23 11:32 UTC, keeprok commented on src/app/(main)/trading/page.tsx
map 을 돌려서 같은 컴포넌트는 하나로 묶어주세요

2024-12-23 12:43 UTC, nrkcode commented
# 카드 컴포넌트화하고 map으로 출력
![image](https://github.com/user-attachments/assets/772960fa-5c25-44d1-8ca3-65a6ca2533d3)

> 카드 두개씩 나눈 이유: 가격 카드는 클릭 이벤트 넣어서 차트 바뀌게 해야하므로 나누었습니다

2024-12-23 12:43 UTC, nrkcode commented on src/app/(main)/trading/page.tsx
수정했습니다!

2024-12-24 02:25 UTC, seongyun4359 approved these changes
- [x] "✅ LGTM"

2024-12-24 02:34 UTC, Giradon approved these changes
- [x] "✅ LGTM"

2024-12-24 05:04 UTC, keeprok reviewed
회의내용 오늘 올라온것까지 수정 해주시면 좋을것같아요

2024-12-24 05:04 UTC, keeprok commented on src/app/(main)/trading/page.tsx
> +	]
이부분같은경우 회의결과 대로 변경해주시길 바랍니다

2024-12-24 05:07 UTC, nrkcode commented
![image](https://github.com/user-attachments/assets/5fe8763e-81d1-4e47-ba9f-85e9cc184aee)

최종_수정했습니다

2024-12-24 05:14 UTC, nrkcode commented on src/app/(main)/trading/page.tsx
> +	]
수정했습니다

2024-12-24 05:14 UTC, keeprok approved these changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->


  - [x] "✅ LGTM"

# Description

2024-12-24 05:29 UTC, merged