feat: 메인 대시보드 ui 레이아웃 구성
turbinecrew/turbin_electrical pull request #37
Opened 2024-12-25 12:19 UTC by seongyun4359

## 🔥 Issues

issue: [KAN-47](https://turbinelectrical.atlassian.net/browse/KAN-47)

<br/>
<br/>

## 🎯 작업 내용
대시보드 ui 작업했습니다.
코드 보시면, 차트 컴포넌트들과 카드 컴포넌트 전부 분리했고, 메인페이지에서 컴포넌트로 넣었습니다.
하이드레이션 에러는 아직 나는 것 같습니다. 
bid pie 차트에 소규모 에러(타입 관련) 확인했습니다. 
크리스마스라서 이만 퇴근하고, 내일 뵐게요 !!

p.s. 노트북 바꿀 것 같습니다 🤓

![image](https://github.com/user-attachments/assets/a6c101e4-d33e-4a0d-a032-17e78867381b)
![image](https://github.com/user-attachments/assets/a7e5546a-487b-4954-87c5-79d09873197b)
![image](https://github.com/user-attachments/assets/619916dd-6978-4c2b-82d5-4284ae37b031)

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] Issue 번호 설정 확인
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-12-25 13:33 UTC, keeprok requested changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

  - [x] "🚧 재고해주시길.."


<!--
  - [x] "✅ LGTM"
-->

# Description
ui 는좋은데요?

2024-12-25 13:33 UTC, keeprok commented on src/app/(main)/page.tsx
> +				{miniCardDatas.map((item, index) => (
index - idx 로 사용하기로 한것같네요

2024-12-25 13:33 UTC, keeprok commented on src/features/realtime/types/weeklyPower/index.ts
> +	잔여거래량: number
이부분같은경우 변수명을 한글로 하는게 정의 된게 아니니 영어로 정의하는게 좋아보이네요

2024-12-25 20:19 UTC, nrkcode approved these changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->


  - [x] "✅ LGTM"

# Description
수고하셨습니다!

2024-12-26 07:05 UTC, Giradon approved these changes
- [x] "✅ LGTM"

2024-12-26 07:53 UTC, keeprok approved these changes

2024-12-26 07:53 UTC, merged