Design/region contents
turbinecrew/turbin_electrical pull request #40
Opened 2024-12-26 13:31 UTC by Giradon

## 🔥 Issues

* issue: [KAN-40](https://turbinelectrical.atlassian.net/browse/KAN-40)
* sub-issues:
   - [KAN-42](https://turbinelectrical.atlassian.net/browse/KAN-42)
   - [KAN-43](https://turbinelectrical.atlassian.net/browse/KAN-43)
   - [KAN-44](https://turbinelectrical.atlassian.net/browse/KAN-44)
<br/>
<br/>

## 🎯 작업 내용

[🎨: region 페이지 디자인](https://github.com/turbinecrew/turbin_electrical/commit/4e8eeb664835e167fcb6479f83029e4fc1e1a2c1)
[🎨: 상단부분 차트 디자인](https://github.com/turbinecrew/turbin_electrical/commit/f3bf8a4a081985301a64e8915476cc4172a1f278)
[🎨: 하단 표 디자인](https://github.com/turbinecrew/turbin_electrical/commit/dc265aaed8ff2f89d6ba45d03ae80cc7eda47d70)
<br/>
<br/>
![image](https://github.com/user-attachments/assets/a152e736-3b92-4a1a-a0d7-7478c3d84630)
<br/>
상단부분 지역별 기상 데이터에 일사량 막대그래프, 기온, 풍속 선그래프 추가<br/>
상단부분 날짜별 예측 발전량 차트 디자인 추가<br/>

하단부분 지역별 발전량 예측 표 디자인 추가

## ✅ 체크 리스트

- [ ] Main 브랜치 Pull 받기
- [ ] Issue 번호 설정 확인
- [ ] Label 확인
- [ ] Assignees 설정 확인
- [ ] Reviewers 설정 확인

<br/>
<br/>

---

#### 🙏 꼭 리뷰 남겨주세요.!!

- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-12-26 14:39 UTC, seongyun4359 reviewed
주석 제거, 그래프 우측 ui가 깨져있습니다. 간격 조정필요해보입니다.

<@$@$@> 이 부분도 props 명 변경부탁드려요.
다른 방식이 더 나을 거 같긴 한데, 잘 모르겠어서... 일단 props만

2024-12-26 14:39 UTC, seongyun4359 commented on src/app/(main)/region/page.tsx
> +			{/* 차트 섹션 */}
주석 제거 부탁드립니당
이 부분 외에도 주석이 많아요.

2024-12-26 14:39 UTC, seongyun4359 commented on src/features/region/components/regionselect/index.tsx
> +const RegionSelect: React.FC<RegionSelectProps> = ({
이 형식보다는 다른 형식 부탁드려요.

2024-12-27 09:21 UTC, keeprok requested changes
또한 지역별차트 사진도 같이올려주시고 사진같은경우 비율 맞춰서 올려주세요

2024-12-28 05:05 UTC, seongyun4359 commented on src/features/region/hooks/data/useFilteredData.ts
> +import type { DataEntry } from "../../types/regionTable"
절대경로로 부탁드려용

2024-12-28 05:05 UTC, seongyun4359 commented on src/features/region/hooks/data/useRegions.ts
> +import type { DataEntry } from "../../types/regionTable"
얘도 절대경로로 수정 부탁드립니다

2024-12-28 05:06 UTC, seongyun4359 commented on src/features/region/components/regionselect/index.tsx
> +const RegionSelect: React.FC<RegionSelectPT> = ({
이거 형태 function 으로 변경 부탁드려요

2024-12-28 08:06 UTC, Giradon commented on src/features/region/components/regionselect/index.tsx
> +const RegionSelect: React.FC<RegionSelectPT> = ({
[⚡️: RegionSelect component function형태롤 변환](https://github.com/turbinecrew/turbin_electrical/pull/40/commits/74125f27e9ddde94b2e857b9dc9cd86b23cc0800)
수정했습니다

2024-12-28 08:06 UTC, Giradon commented on src/features/region/hooks/data/useRegions.ts
> +import type { DataEntry } from "../../types/regionTable"
[⚡️: DataEntry import 경로 절대경로 변경](https://github.com/turbinecrew/turbin_electrical/pull/40/commits/10ecd6b0dd39a89a41c884e5ba462fbb7c73f29a)
수정했습니다

2024-12-28 08:09 UTC, Giradon commented on src/app/(main)/region/page.tsx
> +			{/* 차트 섹션 */}
[⚡️: region page 주석 삭제](https://github.com/turbinecrew/turbin_electrical/pull/40/commits/8101d5841d67168134357acc520f1c646c307794)
수정했습니다

2024-12-29 01:49 UTC, seongyun4359 approved these changes
- [x] "✅ LGTM"

2024-12-29 08:39 UTC, nrkcode reviewed
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->


  - [x] "🚧 재고해주시길.."



  - [x] "✅ LGTM"


# Description

2024-12-29 08:39 UTC, nrkcode commented on src/features/prediction/components/ChartToggle.tsx
> +							? "border-b-4 border-tbGreen font-semibold text-tbGreen"
border-b-4를 공통으로 해도 될거같아요

2024-12-29 10:01 UTC, Giradon commented on src/features/prediction/components/ChartToggle.tsx
> +							? "border-b-4 border-tbGreen font-semibold text-tbGreen"
[⚡️: charttoggle 공통 스타일 설정](https://github.com/turbinecrew/turbin_electrical/pull/40/commits/267b0b9bbcbd23a311dad13cd90fb26eb8dff21c)
수정했습니다.

2024-12-29 20:41 UTC, nrkcode approved these changes
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->


  - [x] "✅ LGTM"


# Description
수고하셨습니다

2024-12-30 03:00 UTC, Giradon commented on src/features/region/components/regionselect/index.tsx
> +			))}
[🏷️: 지역선택 파일 타입수정](https://github.com/turbinecrew/turbin_electrical/pull/40/commits/175814fa4f95134ebcc516268d7149889a73fa52)
수정했습니다.

2024-12-30 03:00 UTC, Giradon commented on src/features/region/components/regionselect/index.tsx
> +
[🏷️: 지역선택 파일 타입수정](https://github.com/turbinecrew/turbin_electrical/pull/40/commits/175814fa4f95134ebcc516268d7149889a73fa52)
수정했습니다.

2024-12-31 07:44 UTC, seongyun4359 approved these changes
- [x] "✅ LGTM"

2024-12-31 13:18 UTC, keeprok approved these changes

2024-12-31 13:19 UTC, keeprok commented
다음 pr은 필터 하면되실것같아요

2024-12-31 14:06 UTC, merged